class NoProcessedFlightLogError(Exception): ...


class MultipleChildLogsError(Exception): ...


class NoLogsFoundError(Exception): ...


class NoDeviceStateError(Exception): ...


class UnknownDeviceError(Exception): ...
